#!/usr/bin/env bash
# Level-watch sweep for cron. Runs check_levels.py and writes the report into
# the repo's data layer (data/Reports/_meta/Level-Watch.md).
#
# Crontab line:
#   17 8,20 * * * $HOME/Documents/projects/market-research/engine/cron_sweep.sh
set -euo pipefail
cd "$(dirname "$0")"

OUT="../data/Reports/_meta/Level-Watch.md"
{
  echo "# Level Watch (auto-generated by check_levels.py cron — do not edit)"
  echo
  echo "Last run: $(date '+%F %H:%M')"
  echo
  .venv/bin/python check_levels.py
} > "$OUT" 2>&1
